services:
  bitcoin:
    image: bitcoin/bitcoin:29.0
    ports:
      - "18443:18443"
      - "18444:18444"
    command: -printtoconsole -regtest=1 -rpcuser=username -rpcpassword=password -server=1 -rpcbind=0.0.0.0 -rpcallowip=0.0.0.0/0
    volumes:
      - "bitcoin:/home/bitcoin/.bitcoin"

volumes:
  bitcoin: {}
