// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/moroz/kinu-no-michi/lib/encrypt"
	"github.com/shopspring/decimal"
)

type Cart struct {
	ID         uuid.UUID
	InsertedAt pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}

type CartItem struct {
	ID         uuid.UUID
	CartID     uuid.UUID
	ProductID  uuid.UUID
	Quantity   decimal.Decimal
	InsertedAt pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}

type Order struct {
	ID             uuid.UUID
	EmailEncrypted encrypt.EncryptedBytes
	GrandTotalEur  decimal.Decimal
	GrandTotalBtc  decimal.Decimal
	ExchangeRate   decimal.Decimal
	InsertedAt     pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type OrderLineItem struct {
	ID           uuid.UUID
	OrderID      uuid.UUID
	ProductID    *uuid.UUID
	Quantity     decimal.Decimal
	UnitPriceEur decimal.Decimal
	SubtotalBtc  decimal.Decimal
	ProductTitle string
	InsertedAt   pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}

type Product struct {
	ID           uuid.UUID
	Title        string
	Slug         string
	BasePriceEur decimal.Decimal
	Description  *string
	ImageUrl     *string
	InsertedAt   pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}
