// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type Product struct {
	ID           pgtype.UUID
	Title        string
	Slug         string
	BasePriceEur decimal.Decimal
	Description  *string
	ImageUrl     *string
	InsertedAt   pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}
